services:
  postgres:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DATABASE: postgres
    volumes:
        - ./mounts/postgres/:/docker-entrypoint-initdb.d/
        # - ./mounts/postgres/data:/var/lib/postgresql/data
    networks:
      - dunger_backend_net
  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
    ports:
      - '5050:80'
    networks:
      - dunger_backend_net

networks:
  dunger_backend_net:
    name: dunger_backend_net
    external: true