services:
  gpt:
    image: node:latest
    ports: 
      - 4000:3000
    volumes:
      - ../shared/prisma:/nest-app/prisma
      - ./:/nest-app/
    working_dir: /nest-app/
    entrypoint: bash -c "yarn install && npm run g:start"

