services:
  nest:
    image: node:latest
    ports: 
      - 3000:3000
    volumes:
      - ../shared/prisma:/nest-app/prisma
      - ./:/nest-app/
    working_dir: /nest-app/
    entrypoint: bash -c "yarn install && npx prisma generate && npx prisma migrate deploy && npx ts-node --transpile-only ./prisma/seeds/seed-all.ts &&  npm run b:start"
    networks:
      - dunger_backend_net

  postgres:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DATABASE: postgres
    # volumes:
        # - ./mounts/postgres/:/docker-entrypoint-initdb.d/
        # - ./mounts/postgres/data:/var/lib/postgresql/data
    networks:
      - dunger_backend_net
  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
    ports:
      - '5050:80'
    networks:
      - dunger_backend_net

networks:
  dunger_backend_net:
    name: dunger_backend_net
    driver: bridge
    # external: true
