name: Deploy Dunger Applications

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    
env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  deploy:
    runs-on: ["self-hosted"]
    environment: prod         
    permissions:
      deployments: write 
      contents: read
    steps:
      - name: Install jq
        run: |
          sudo apt-get update && sudo apt-get install -y jq
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup web env
        run: |
          echp | curl -s -H "Authorization: token $GH_TOKEN" \
          "https://api.github.com/repos/$GITHUB_REPOSITORY/environments/prod/variables" \
          # | jq -r '.variables[] | "\(.name)=\(.value)"' > packages/frontend/dunger-user-web/.env

      - name: Build and run Dunger User Web
        run: |
          docker build -t dunger-user-web -f packages/frontend/dunger-user-web/Dockerfile .
          docker stop dunger-user-web-container || true && docker rm dunger-user-web-container || true
          docker run -d -p 5173:8080 --name dunger-user-web-container --env-file packages/frontend/dunger-user-web/.env dunger-user-web

      - name: Build and run Dunger Core
        run: |
          docker build -t dunger-core -f packages/backend/dunger-core/Dockerfile .
          docker stop dunger-core-container || true && docker rm dunger-core-container || true
          docker network create dunger_backend_net || true
          docker run -d -p 3000:3000 --name dunger-core-container --network dunger_backend_net --env-file packages/backend/dunger-core/.env dunger-core
